### ISSUE TITLE
Many Go binaries being flagged with `net/hostport/parse` and `process/multithreaded` in diffs

### ISSUE THREAD

**Issue by mattmoor** [chainguard-dev/bincapz#94] opened 2024-04-02 20:36 UTC
For example this Rekor bump: https://github.com/wolfi-dev/os/pull/16151

I believe these are: https://github.com/chainguard-dev/bincapz/blob/main/rules/net/hostport-parse.yara
and: https://github.com/chainguard-dev/bincapz/blob/main/rules/process/multithreaded.yara

I want to say I have seen these in a pretty significant volume of PRs.  I'm not sure if maybe it is a difference in the underlying toolchain or some extremely common dependency, but I wanted to flag the noise it's causing.

**Comment by mattmoor** [comment] 2024-04-02 20:36
Here's another one: https://github.com/wolfi-dev/os/pull/16154

**Comment by tstromberg** [comment] 2024-05-07 02:14
Closing this as I believe it to be intended behavior as the contents have changed - even if it's weird. Both rules seem to be doing the correct thing. I'd consider marking the "multithreaded" rules `harmless`, but it did show up as an unexpected change for 3CX.

My recommendation is to focus on behavioral changes that change the risk level.

**Closed by tstromberg** 2024-05-07 02:14 UTC
